const E=PandaEngine, C=GAME_CONTENT, $=s=>document.querySelector(s);
let save={best:{},sound:true};try{save={...save,...JSON.parse(localStorage.getItem('panda-post-v1')||'{}')};}catch{}
let chapter=0,state=null,raf=0,audioContext=null;
const persist=()=>{try{localStorage.setItem('panda-post-v1',JSON.stringify(save));}catch{}};
const unlocked=()=>Math.min(25,Math.max(0,...Object.keys(save.best).map(Number))+1);
function beep(ok){if(!save.sound)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();const o=audioContext.createOscillator(),g=audioContext.createGain();o.connect(g);g.connect(audioContext.destination);o.frequency.value=ok?660:190;g.gain.setValueAtTime(.055,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.15);o.start();o.stop(audioContext.currentTime+.16);}catch{}}
function showModal(html){$('#modalContent').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();}
function zoomCity(level){
 const viewer=document.createElement('dialog');viewer.className='city-viewer';viewer.setAttribute('aria-label',E.cities[level-1]+' · '+CITY_FEATURES[level-1]);
 viewer.innerHTML=`<button class="secondary city-viewer-close" autofocus>× 关闭</button>${cityTile(level)}<div class="city-viewer-caption">${E.cities[level-1]} · ${CITY_FEATURES[level-1]}</div>`;
 document.body.append(viewer);viewer.querySelector('button').onclick=()=>viewer.close();
 viewer.addEventListener('click',e=>{if(e.target===viewer){const r=viewer.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)viewer.close();}});
 viewer.addEventListener('close',()=>viewer.remove());viewer.showModal();
}
function closeModal(){$('#modal').close();}
function art(){return '<img class="courier-art" src="assets/panda.png" alt="熊猫快递员">';}
function home(){cancelAnimationFrame(raf);state=null;closeModal();const next=unlocked();chapter=Math.floor((next-1)/5);renderHome();}
function renderHome(){const next=unlocked(),done=Object.keys(save.best).length;
 $('#main').innerHTML=`<section class="hero"><div><div class="eyebrow">成都始发 · 公路快线</div><h1>熊猫<em>快递局</em></h1><p>下一站，送达美好。</p><div class="actions"><button class="primary" id="continueBtn">${done?'继续旅程':'开始第一站'} <span>→</span></button></div></div>${art()}</section><div class="section-top"><h2>快递旅程</h2><span>★ ${Object.values(save.best).reduce((n,x)=>n+x.stars,0)} / 75</span></div><div class="chapters">${['熊猫出川','一路向东','北上北京','南下广州','开往春城'].map((x,i)=>`<button class="chapter ${i===chapter?'selected':''}" data-chapter="${i}">0${i+1} ${x}</button>`).join('')}</div><div class="level-grid">${C.slice(chapter*5,chapter*5+5).map(x=>stationCard(x,next)).join('')}</div>`;
 $('#continueBtn').onclick=()=>prepare(next);
 document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>{chapter=+b.dataset.chapter;renderHome();});
 document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>prepare(+b.dataset.level));
}
function prepare(level,practiceOnly=false){cancelAnimationFrame(raf);closeModal();const basketKinds=E.kinds(level).slice();for(let i=basketKinds.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[basketKinds[i],basketKinds[j]]=[basketKinds[j],basketKinds[i]];}state={level,practiceOnly,basketKinds,mode:'ready',index:0,correct:0,passed:0,missed:0,wrong:0,elapsed:0,seq:E.sequence(level),phase:0,last:0,paused:false,practiceIndex:0};renderGame();
 overlay(`<div class="eyebrow">第 ${level} 站 · ${E.cities[level-1]}</div><h2>对上图案，入框就点</h2>${rulePictures(level)}${tutorialArt(level)}<div class="actions"><button class="primary" id="startPractice">${level<=3||practiceOnly?'试一试':'练习'}</button>${level>3&&!practiceOnly?'<button class="secondary" id="startOfficial">出发 →</button>':''}</div><button class="quiet rule-detail" id="ruleDetail">规则 ⓘ</button>`);
 $('#ruleDetail').onclick=()=>showModal(`<h2>本关规则</h2><p>${C[level-1].rule}</p><p>快递中心进入对应篮框时点击。框外点击无效。</p><button class="primary" onclick="closeModal()">知道了</button>`);
 $('#startPractice').onclick=practiceStart;if($('#startOfficial'))$('#startOfficial').onclick=countdown;
}
function dual(){return [16,17,20,22,25].includes(state.level);}
function symbol(k){return k.replace('蓝色','').replace('橙色','').replace('黄色','').replace('紫色','').replace('双竹叶','竹竹').replace('单竹叶','竹').replace('竹叶','竹').replace('花朵','✿').replace('双圆点','••').replace('单圆点','•').replace('三圆点','•••').replace('圆点','•').replace('实心星形','★').replace('空心星形','☆').replace('实心圆形','●').replace('圆形','●').replace('方形','■').replace('三角形','▲').replace('星形','★').replace('向右','→').replace('向左','←').replace('向上','↑').replace('向下','↓')||'●';}
function color(k){return k.includes('蓝')?'blue':k.includes('橙')?'orange':k.includes('紫')?'purple':k.includes('黄')?'yellow':'';}
function renderGame(){const {level}=state;
 $('#main').innerHTML=`<div class="game-heading"><div><span class="eyebrow">${C[level-1].chapter} / ${level<6?'G42':level<11?'G42':level<16?'G2':level<21?'G4':'G80'}</span><h1>第 ${String(level).padStart(2,'0')} 站 · ${E.cities[level-1]}</h1></div><div class="game-tools"><button class="primary back-home" id="backHomeBtn">← 返回首页</button><button class="quiet" id="retryBtn">重来</button><button class="secondary" id="pauseBtn">暂停</button></div></div><div class="stats"><div class="stat">已处理<strong id="processed">0 / ${E.ROUND.total}</strong></div><div class="stat">✓ 入篮<strong id="correct">0</strong></div><div class="stat">◷<strong id="timeLeft">—</strong></div><div class="progress-track"><i id="progress" style="width:0"></i></div></div><div class="rule-banner"><span id="ruleText">${rulePictures(level)}</span></div><section class="warehouse ${dual()?'two-lanes':''}" id="warehouse"><div class="warehouse-top"><span>➜</span><span id="laneHint">传送方向 →</span></div><div id="lanes"></div><div class="game-bottom"><div id="feedback" class="feedback" aria-live="polite">入框，再点。</div><button class="spacekey" id="deliverBtn" aria-label="投递当前快递">投递 <small>空格</small></button></div></section>`;
 $('#backHomeBtn').onclick=()=>confirmLeave(home,'返回旅程首页？');$('#retryBtn').onclick=()=>confirmLeave(()=>prepare(level,state.practiceOnly),'重新开始本关？');$('#pauseBtn').onclick=togglePause;$('#deliverBtn').onclick=()=>投递();renderLanes();
}
function renderLanes(){const ks=state.basketKinds;$('#lanes').innerHTML=Array.from({length:dual()?2:1},(_,lane)=>`<div class="lane" id="lane${lane}"><span class="lane-name">${dual()?lane?'右线':'左线':'分拣传送带'}</span><div class="belt"></div>${ks.map((k,i)=>`<div class="basket" data-lane="${lane}" data-basket="${i}" style="left:${[25,52,79][i]}%"><div class="basket-body"><img src="assets/basket.png" alt=""><span title="${k}">${itemIcon(k)}</span></div></div>`).join('')}<button class="parcel done" id="parcel${lane}" aria-label="点击投放快递"></button></div>`).join('');document.querySelectorAll('.parcel').forEach(p=>p.onclick=()=>投递());}
function overlay(html){$('#warehouse .overlay')?.remove();const d=document.createElement('div');d.className='overlay';d.innerHTML=html;$('#warehouse').append(d);}
function removeOverlay(){$('#warehouse .overlay')?.remove();}
function practiceStart(){state.mode='practice';state.practiceIndex=0;state.correct=0;state.passed=0;state.missed=0;state.wrong=0;state.phase=0;renderLanes();removeOverlay();nextPractice();state.last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(tick);}
function nextPractice(){const k=E.kinds(state.level,0);let kind=k[0],stamp=false,yes=true;if(state.practiceIndex===1){stamp=state.level>=4;kind=stamp?k[0]:k[2];yes=false;}if(state.practiceIndex===2){kind=state.level===4?k[1]:k[0];}state.current={kind,lane:0,active:0,stamp,yes,phase:0};state.elapsed=0;state.resolved=false;mountParcel();feedback(`${state.practiceIndex+1} / 3 · ${yes?'入框就点':'让它通过'}`);}
function countdown(){state.mode='countdown';state.count=3;state.elapsed=0;state.phase=0;renderLanes();overlay('<span class="eyebrow">准备发车</span><div class="count">3</div>');state.last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(tick);}
function officialStart(){state.mode='playing';state.index=0;state.correct=0;state.passed=0;state.missed=0;state.wrong=0;state.elapsed=0;state.phase=0;state.seq=E.sequence(state.level);removeOverlay();mountCurrent();}
function mountCurrent(){state.current=state.seq[state.index];state.elapsed=0;state.resolved=false;if(state.phase!==state.current.phase){state.phase=state.current.phase;renderLanes();}mountParcel();}
function mountParcel(){document.querySelectorAll('.parcel').forEach(p=>p.classList.add('done'));const c=state.current,p=$('#parcel'+c.lane);p.innerHTML=`<div class="box"><img src="assets/parcel.png" alt=""><span class="label" title="${c.kind}">${itemIcon(c.kind)}</span>${c.stamp?'<i class="stamp">×</i>':''}</div>`;p.style.left='5%';p.classList.remove('done');p.setAttribute('aria-label',c.kind+(c.stamp?'，不合格':'')+'快递，点击投放');if(state.level===17){$('#laneHint').textContent=`当前可投车道：${c.active?'右':'左'}`;document.querySelectorAll('.lane').forEach((x,i)=>x.classList.toggle('lit',i===c.active));}if(state.level===13)$('#ruleText').innerHTML=rulePictures(state.level,state.phase);updateStats();}
function travel(){const duration=state.mode==='practice'?6.5:E.duration(state.level,state.index);return {duration,x:E.position(state.elapsed,duration)};}
function 投递(){if(!state||!['practice','playing'].includes(state.mode)||state.paused||state.resolved||$('#modal').open)return;const {duration,x}=travel();const b=E.hit(x);if(state.elapsed>=duration-.25||b<0){feedback('等入框',true);return;}const c=state.current,ok=c.yes&&state.basketKinds[b]===c.kind;state.resolved=true;state.resolvedAt=state.elapsed;const parcel=$('#parcel'+c.lane),ghost=parcel.cloneNode(true);ghost.removeAttribute('id');ghost.disabled=true;ghost.style.left=x*100+'%';ghost.style.pointerEvents='none';parcel.parentNode.append(ghost);ghost.animate(ok?[{transform:'translateX(-50%)',opacity:1},{transform:'translate(-50%, 65px) scale(.5)',opacity:0}]:[{transform:'translateX(-50%)',opacity:1},{transform:'translate(-50%, -35px) rotate(15deg)',opacity:0}],{duration:330,easing:'ease-in',fill:'forwards'}).onfinish=()=>ghost.remove();parcel.classList.add('done');
 if(ok){state.correct++;feedback('✓ 送达！');beep(true);}else{if(c.yes)state.missed++;else state.wrong++;feedback(c.stamp?'× 章要放过':!c.yes?'这件要放过':'篮子不对',true);beep(false);}state.practiceOk=ok;updateStats();}
function feedback(text,bad=false){$('#feedback').textContent=text;$('#feedback').className='feedback'+(bad?' bad':'');}
function endParcel(){if(!state.resolved){if(state.current.yes){state.missed++;feedback('错过啦',true);state.practiceOk=false;}else{state.passed++;feedback('✓ 正确放过');state.practiceOk=true;}}if(state.mode==='practice'){
   const ok=state.practiceOk;if(ok)state.practiceIndex++;
   state.mode='practiceWait';overlay(`<h2>${ok?'✓ 漂亮！':'再试一次'}</h2><div class="practice-dots">${'●'.repeat(state.practiceIndex)+'○'.repeat(3-state.practiceIndex)}</div>${ok?'':tutorialArt(state.level)}<button class="primary" id="practiceNext">${ok&&state.practiceIndex===3?state.practiceOnly?'再练一次':'正式出发':'继续练习'}</button>${ok&&state.practiceIndex===3?'<button class="quiet" id="practiceHome">返回首页</button>':''}`);
   $('#practiceNext').onclick=()=>{if(state.practiceIndex===3){state.practiceOnly?practiceStart():countdown();}else{state.mode='practice';removeOverlay();nextPractice();state.last=performance.now();raf=requestAnimationFrame(tick);}};if($('#practiceHome'))$('#practiceHome').onclick=home;return;
 }
 state.index++;updateStats();if(state.index===E.ROUND.total){finish();return;}if(state.level===13&&state.index===E.ROUND.switchAt){state.mode='switch';state.elapsed=0;overlay('<h2>换班啦</h2>'+rulePictures(13,1)+'<div class="count">3</div>');return;}mountCurrent();}
function updateStats(){if(!state)return;$('#processed').textContent=state.mode==='practice'?`${state.practiceIndex} / 3`:`${state.index} / ${E.ROUND.total}`;$('#correct').textContent=state.correct;$('#progress').style.width=state.index/E.ROUND.total*100+'%';if(state.mode==='practice')$('#timeLeft').textContent='慢速';else{let seconds=state.level===13&&state.index<E.ROUND.switchAt?3:0;for(let i=state.index;i<E.ROUND.total;i++)seconds+=E.duration(state.level,i);$('#timeLeft').textContent=Math.max(0,Math.ceil(seconds-state.elapsed))+' 秒';}}
function tick(now){if(!state)return;const dt=Math.min((now-state.last)/1000,.08);state.last=now;if(state.paused){raf=requestAnimationFrame(tick);return;}
 if(state.mode==='countdown'||state.mode==='switch'){state.elapsed+=dt;const n=3-Math.floor(state.elapsed);if(n>0){$('.count').textContent=n;}else if(state.mode==='countdown')officialStart();else{state.mode='playing';removeOverlay();mountCurrent();}}
 else if(['playing','practice'].includes(state.mode)){state.elapsed+=dt;const {duration,x}=travel();const p=$('#parcel'+state.current.lane);p.style.left=x*100+'%';document.querySelectorAll('.basket').forEach(b=>b.classList.toggle('active',!state.resolved&&+b.dataset.lane===state.current.lane&&E.hit(x)===+b.dataset.basket&&state.elapsed<duration-.25));updateStats();if(state.elapsed>=duration||(state.resolved&&state.elapsed-state.resolvedAt>=.35))endParcel();}
 if(state&&['playing','practice','countdown','switch'].includes(state.mode))raf=requestAnimationFrame(tick);
}
function togglePause(){if(!state||!['playing','practice','countdown','switch'].includes(state.mode))return;if(!state.paused){state.paused=true;showModal('<div class="eyebrow">休息一下</div><h2>分拣已暂停</h2><img class="pause-panda" src="assets/panda.png" alt="休息中的熊猫快递员"><div class="modal-actions"><button class="primary" id="resume">继续分拣</button><button class="secondary" id="pauseHome">返回首页</button></div>');$('#resume').onclick=()=>{closeModal();state.paused=false;state.last=performance.now();};$('#pauseHome').onclick=home;}}
function confirmLeave(action,title){if(!state||['ready','result','practiceWait'].includes(state.mode)){action();return;}state.paused=true;showModal(`<h2>${title}</h2><p>本局将重新开始，旅程进度保留。</p><div class="modal-actions"><button class="primary" id="confirm">确定</button><button class="secondary" id="cancel">继续当前游戏</button></div>`);$('#confirm').onclick=()=>{closeModal();action();};$('#cancel').onclick=()=>{closeModal();state.paused=false;state.last=performance.now();};}
function finish(){state.mode='result';cancelAnimationFrame(raf);const {level,correct,passed,missed,wrong}=state,r=E.result(level,correct,passed);if(r.win){const old=save.best[level];if(!old||r.score>old.score)save.best[level]={stars:r.stars,score:r.score};persist();}
 showModal(`<div class="eyebrow">${E.cities[level-1]} · 本次分拣完成</div><div class="result-stars">${'★'.repeat(r.stars)+'☆'.repeat(3-r.stars)}</div><h2 class="result-title" tabindex="-1" autofocus>${r.win?level===25?'全程送达，辛苦啦！':'顺利送达！':'再接再厉！'}</h2><div class="result-metrics"><div>投递精准度<strong>${r.score}<small> 分</small></strong></div><div>目标投递率<strong>${(r.target*100).toFixed(1)}%</strong></div><div>正确放过率<strong>${(r.release*100).toFixed(1)}%</strong></div></div><details class="score-details"><summary>成绩详情</summary><p>正确入篮 ${correct} / ${E.ROUND.targets} · 漏投 ${missed}<br>正确放过 ${passed} / ${E.ROUND.releases} · 误投 ${wrong}<br>${C[level-1].threshold}</p></details>${r.win&&level%5===0?`<div class="chapter-seal">✦ 已获得 ${['三峡','上海天际线','祈年殿','广州塔','斗南鲜花'][level/5-1]}纪念章<br><small>${C[level-1].chapter} · 线路已完成</small></div>`:''}<article class="knowledge-card result-knowledge panda-knowledge"><img class="knowledge-panda" src="assets/panda.png" alt="熊猫快递员正在讲解"><div class="knowledge-bubble"><span class="eyebrow">熊猫讲给你听 · ${E.cities[level-1]}</span><button class="knowledge-zoom" aria-label="放大${E.cities[level-1]}图片" onclick="zoomCity(${level})">${cityTile(level)}<span aria-hidden="true">⤢</span></button><p>${C[level-1].knowledge}</p></div></article><div class="modal-actions">${r.win&&level<25?'<button class="primary" id="nextLevel">前往下一站 →</button>':''}<button class="${r.win?'secondary':'primary'}" id="replay">再试一次</button><button class="secondary" id="resultHome">返回首页</button></div>`);
 if($('#nextLevel'))$('#nextLevel').onclick=()=>prepare(level+1);$('#replay').onclick=()=>prepare(level);$('#resultHome').onclick=home;
}
$('#homeBtn').onclick=()=>confirmLeave(home,'返回旅程首页？');
$('#collectionBtn').onclick=()=>{if(state&&state.mode!=='result'&&state.mode!=='ready'){togglePause();return;}showModal(`<div class="eyebrow">沿途的见闻</div><h2>城市知识图鉴</h2><div class="collection">${C.filter(x=>save.best[x.id]).map(x=>`<article><h3>K${String(x.id).padStart(2,'0')} · ${E.cities[x.id-1]}</h3><p>${x.knowledge}</p></article>`).join('')||'<p>还没有收集到知识卡。完成第一站，认识南充与嘉陵江。</p>'}</div><div class="modal-actions"><button class="primary" id="closeCollection">关闭</button></div>`);$('#closeCollection').onclick=closeModal;};
$('#soundBtn').onclick=()=>{save.sound=!save.sound;persist();$('#soundBtn').textContent='音效 '+(save.sound?'开':'关');};$('#soundBtn').textContent='音效 '+(save.sound?'开':'关');
$('#modal').addEventListener('cancel',e=>{if(state?.paused)e.preventDefault();});
document.addEventListener('keydown',e=>{if(e.code==='Space'&&state&&['playing','practice'].includes(state.mode)&&!$('#modal').open){e.preventDefault();if(!e.repeat)投递();}if(e.code==='Escape'&&!$('#modal').open)togglePause();});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&state&&!state.paused)togglePause();});
home();
